In [ ]:
%load_ext autoreload
%autoreload 2

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from IPython.display import display, clear_output
import ipywidgets as widgets
import plotly.graph_objects as go

import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from parentHelpers import *
# from loanPipelineHelpers import *
# from regression import *
# from helperProjectDriver import *
# from helperProjectAlamo import *
# from databaseHelpers import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [13]:
folder = "C:\\Users\\YuemengZhang\\OneDrive - Bayview Asset Management, LLC\\C&SBL Deal Channels - Documents\\PNC\\PNC Data June 2026\\"

In [14]:
charge_off_loans_location = Path("Data\\all_charge_off_PIF_student_ever_mask_PII[1].xlsx")
payment_history_location = Path(folder + "student full hist raw acct\student_full_hist_raw_acct_(1)[1].csv")
loan_tape_location = Path(folder + "PNC_Student_Loan_Tape_04-2026_v1 - MASKED - For Transmission\PNC_Student_Loan_Tape_04-2026_v1_-_MASKED[1].csv")

In [15]:
charge_off_loans = read_in_files(charge_off_loans_location, engine="openpyxl")
payment_history = read_in_files(payment_history_location)
loan_tape = read_in_files(loan_tape_location, encoding="cp1252")

Shape of the dataframe: (221866, 9)

,Account ID Mask,x_period_end_dt,PORT_GROUP_ROLLED_X,x_rpymt_dt,open_dt,final_status,X_CONTRACTUAL_BALANCE_AMT,dec_fico_scr,chargeoff_flag
0,1,2024-05-31,Run Off,2010-02-10,2007-08-29 00:00:00,S. PIF_CREDIT_BALANCES,0.0,NaN,0
1,2,2017-12-31,Run Off,2009-03-14,2008-03-30 00:00:00,S. PIF_CREDIT_BALANCES,0.0,NaN,0
2,3,2011-12-31,Run Off,2009-02-14,NaN,S. PIF_CREDIT_BALANCES,0.0,NaN,0
3,4,2014-11-30,Run Off,2009-08-15,2006-09-06 00:00:00,S. PIF_CREDIT_BALANCES,0.0,NaN,0
4,5,2015-06-30,Run Off,2009-02-17,2008-01-13 00:00:00,S. PIF_CREDIT_BALANCES,0.0,NaN,0
...,...,...,...,...,...,...,...,...,...
221861,221862,2018-07-31,Grove City,2006-04-26,1999-08-28 00:00:00,S. PIF_CREDIT_BALANCES,0.0,NaN,0
221862,221863,2018-07-31,Grove City,2003-11-22,1998-08-31 00:00:00,S. PIF_CREDIT_BALANCES,0.0,NaN,0
221863,221864,2018-07-31,Grove City,2003-11-11,2000-08-28 00:00:00,S. PIF_CREDIT_BALANCES,0.0,NaN,0
221864,221865,2018-07-31,Grove City,2003-11-11,1999-08-25 00:00:00,S. PIF_CREDIT_BALANCES,0.0,NaN,0
221865,221866,2018-07-31,Grove City,2003-11-11,1999-08-25 00:00:00,S. PIF_CREDIT_BALANCES,0.0,NaN,0

Shape of the dataframe: (3707733, 13)

,acct_id_mask,load_date,sub_products,final_status,repayment_dt_vintage,cosign_ind_x,open_dt_vintage,dec_fico_scr,balance,dpd30_bal,dpd60_bal,dpd90_bal,gcl
0,1,2022-12-31,Solution,A.SCHOOL,2025.0,Cosigned,2021,777.0,5553.00,0.0,0.0,0.0,NaN
1,1,2023-01-31,Solution,A.SCHOOL,2025.0,Cosigned,2021,777.0,5553.00,0.0,0.0,0.0,NaN
2,1,2023-02-28,Solution,A.SCHOOL,2025.0,Cosigned,2021,777.0,5553.00,0.0,0.0,0.0,NaN
3,1,2023-03-31,Solution,A.SCHOOL,2025.0,Cosigned,2021,777.0,5553.00,0.0,0.0,0.0,NaN
4,1,2023-04-30,Solution,A.SCHOOL,2025.0,Cosigned,2021,777.0,5553.00,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3707728,125377,2022-12-31,McKinsey,C.DEFERMENT,2022.0,Noncosigned,2021,0.0,32493.97,0.0,0.0,0.0,NaN
3707729,125377,2023-01-31,McKinsey,C.DEFERMENT,2022.0,Noncosigned,2021,0.0,31536.52,0.0,0.0,0.0,NaN
3707730,125377,2023-02-28,McKinsey,S. PIF_CREDIT_BALANCES,2022.0,Noncosigned,2021,0.0,0.00,0.0,0.0,0.0,NaN
3707731,125377,2023-03-31,McKinsey,S. PIF_CREDIT_BALANCES,2022.0,Noncosigned,2021,0.0,0.00,0.0,0.0,0.0,NaN
3707732,125377,2023-04-30,McKinsey,S. PIF_CREDIT_BALANCES,2022.0,Noncosigned,2021,0.0,0.00,0.0,0.0,0.0,NaN

g:\YuemengZhang\Deal Opportunities - Clean\loanPipelineHelpers.py:33: DtypeWarning: Columns (0,1,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,26,27,36,37,38,39,42,43,44,45,46,49,50,55,56,57,59,67,68,69,70,85,87,89,90,91,92,94,96) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(path, **kwargs)

Shape of the dataframe: (204686, 97)

,loan_servicer,date_of_portfolio_info,account_mask,borrower_id_mask,co_borrower_id_mask,source_system_id,product,sub_product,product_type,portfolio_subgroup,...,school_type,loan_sequence_number,lifecycle_status,guarantor,repayment_schedule_type,servicing_data_date,charge_off_recovery_data_date,application_data_date,current_fico_data_date,data_extract_timestamp
0,700100,2026-04-30,1.0,1164185.0,NaN,SLA,PRIVATE,ACCESS GROUP,AGBXL,ACCESS GROUP: BAR EXAMINATION LOAN,...,Graduate/Professional (>= 300 hours),5.0,REPAYMENT,NaN,LEVEL REPAYMENT SCHEDULE TYPE,2026-04-30,NaN,NaN,20260407.0,2026-06-01 09:36:00.906609000
1,700100,2026-04-30,2.0,1325323.0,NaN,SLA,PRIVATE,ACCESS GROUP,AGBXL,ACCESS GROUP: BAR EXAMINATION LOAN,...,Professional School,1.0,REPAYMENT,NaN,LEVEL REPAYMENT SCHEDULE TYPE,2026-04-30,NaN,NaN,20260407.0,2026-06-01 09:36:00.906609000
2,700100,2026-04-30,3.0,2924861.0,NaN,SLA,PRIVATE,ACCESS GROUP,AGLAW,ACCESS GROUP: LAW ACCESS LOAN,...,4 Year,1.0,REPAYMENT,NaN,LEVEL REPAYMENT SCHEDULE TYPE,2026-04-30,NaN,NaN,20260407.0,2026-06-01 09:36:00.906609000
3,700100,2026-04-30,4.0,2688722.0,NaN,SLA,PRIVATE,ACCESS GROUP,AGBXL,ACCESS GROUP: BAR EXAMINATION LOAN,...,4 Year,2.0,REPAYMENT,NaN,LEVEL REPAYMENT SCHEDULE TYPE,2026-04-30,NaN,NaN,20260407.0,2026-06-01 09:36:00.906609000
4,700100,2026-04-30,5.0,2074250.0,NaN,SLA,PRIVATE,ACCESS GROUP,AGLAW,ACCESS GROUP: LAW ACCESS LOAN,...,Graduate/Professional (>= 300 hours),1.0,REPAYMENT,NaN,LEVEL REPAYMENT SCHEDULE TYPE,2026-04-30,NaN,NaN,20260407.0,2026-06-01 09:36:00.906609000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204685,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
display(payment_history[payment_history["acct_id_mask"] == 2][['acct_id_mask', 'repayment_dt_vintage', 'open_dt_vintage']])

    acct_id_mask  repayment_dt_vintage  open_dt_vintage
39             2                2011.0             2009
40             2                2011.0             2009
41             2                2011.0             2009
42             2                2011.0             2009
43             2                2011.0             2009
44             2                2011.0             2009
45             2                2011.0             2009
46             2                2011.0             2009
47             2                2011.0             2009
48             2                2011.0             2009
49             2                2011.0             2009
50             2                2011.0             2009
51             2                2011.0             2009
52             2                2011.0             2009
53             2                2011.0             2009
54             2                2011.0             2009
55             2                2011.0             2009
56             2                2011.0             2009
57             2                2011.0             2009
58             2                2011.0             2009
59             2                2011.0             2009
60             2                2011.0             2009
61             2                2011.0             2009
62             2                2011.0             2009
63             2                2011.0             2009
64             2                2011.0             2009
65             2                2011.0             2009
66             2                2011.0             2009
67             2                2011.0             2009
68             2                2011.0             2009
69             2                2011.0             2009

In [40]:
display(charge_off_loans[charge_off_loans['Account ID Mask'] == 2][['Account ID Mask', 'x_rpymt_dt', 'open_dt']])

   Account ID Mask x_rpymt_dt              open_dt
1                2 2009-03-14  2008-03-30 00:00:00

In [41]:
loan_tape[loan_tape['account_mask'] == 2][['account_mask', 'repayment_begin_date', 'app_vintage']]

   account_mask repayment_begin_date app_vintage
1           2.0           2008-09-24     2007-08

In [42]:
loan_tape[loan_tape['account_mask'].notna()]

,loan_servicer,date_of_portfolio_info,account_mask,borrower_id_mask,co_borrower_id_mask,source_system_id,product,sub_product,product_type,portfolio_subgroup,...,school_type,loan_sequence_number,lifecycle_status,guarantor,repayment_schedule_type,servicing_data_date,charge_off_recovery_data_date,application_data_date,current_fico_data_date,data_extract_timestamp
0,700100,2026-04-30,1.0,1164185.0,NaN,SLA,PRIVATE,ACCESS GROUP,AGBXL,ACCESS GROUP: BAR EXAMINATION LOAN,...,Graduate/Professional (>= 300 hours),5.0,REPAYMENT,NaN,LEVEL REPAYMENT SCHEDULE TYPE,2026-04-30,NaN,NaN,20260407.0,2026-06-01 09:36:00.906609000
1,700100,2026-04-30,2.0,1325323.0,NaN,SLA,PRIVATE,ACCESS GROUP,AGBXL,ACCESS GROUP: BAR EXAMINATION LOAN,...,Professional School,1.0,REPAYMENT,NaN,LEVEL REPAYMENT SCHEDULE TYPE,2026-04-30,NaN,NaN,20260407.0,2026-06-01 09:36:00.906609000
2,700100,2026-04-30,3.0,2924861.0,NaN,SLA,PRIVATE,ACCESS GROUP,AGLAW,ACCESS GROUP: LAW ACCESS LOAN,...,4 Year,1.0,REPAYMENT,NaN,LEVEL REPAYMENT SCHEDULE TYPE,2026-04-30,NaN,NaN,20260407.0,2026-06-01 09:36:00.906609000
3,700100,2026-04-30,4.0,2688722.0,NaN,SLA,PRIVATE,ACCESS GROUP,AGBXL,ACCESS GROUP: BAR EXAMINATION LOAN,...,4 Year,2.0,REPAYMENT,NaN,LEVEL REPAYMENT SCHEDULE TYPE,2026-04-30,NaN,NaN,20260407.0,2026-06-01 09:36:00.906609000
4,700100,2026-04-30,5.0,2074250.0,NaN,SLA,PRIVATE,ACCESS GROUP,AGLAW,ACCESS GROUP: LAW ACCESS LOAN,...,Graduate/Professional (>= 300 hours),1.0,REPAYMENT,NaN,LEVEL REPAYMENT SCHEDULE TYPE,2026-04-30,NaN,NaN,20260407.0,2026-06-01 09:36:00.906609000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172295,700100.0,2026-04-30,172296.0,155414134.0,NaN,SLA,PRIVATE,ALL OTHER RUN OFF,ALP,TERI GUARANTEED: ALTERNATIVE LOAN PROGRAM,...,NaN,1.0,REPAYMENT,NaN,NaN,2026-04-30,NaN,NaN,20260407.0,2026-06-01 09:36:00.906609000
172296,700100.0,2026-04-30,172297.0,522875537.0,NaN,SLA,PRIVATE,ALL OTHER RUN OFF,PEP,TERI GUARANTEED: GRADUATE/PROFESSIONAL,...,NaN,3.0,REPAYMENT,NaN,LEVEL REPAYMENT SCHEDULE TYPE,2026-04-30,NaN,NaN,20260407.0,2026-06-01 09:36:00.906609000
172297,700100.0,2026-04-30,172298.0,522875537.0,NaN,SLA,PRIVATE,ALL OTHER RUN OFF,PEP,TERI GUARANTEED: GRADUATE/PROFESSIONAL,...,NaN,2.0,REPAYMENT,NaN,LEVEL REPAYMENT SCHEDULE TYPE,2026-04-30,NaN,NaN,20260407.0,2026-06-01 09:36:00.906609000
172298,700100.0,2026-04-30,172299.0,522875537.0,NaN,SLA,PRIVATE,ALL OTHER RUN OFF,ALP,TERI GUARANTEED: ALTERNATIVE LOAN PROGRAM,...,NaN,1.0,REPAYMENT,NaN,LEVEL REPAYMENT SCHEDULE TYPE,2026-04-30,NaN,NaN,20260407.0,2026-06-01 09:36:00.906609000
172299,700100.0,2026-04-30,172300.0,539845862.0,NaN,SLA,PRIVATE,ALL OTHER RUN OFF,PEP,TERI GUARANTEED: GRADUATE/PROFESSIONAL,...,NaN,2.0,REPAYMENT,NaN,NaN,2026-04-30,NaN,NaN,20260407.0,2026-06-01 09:36:00.906609000

In [51]:
loan_tape['portfolio_subgroup'].value_counts()

portfolio_subgroup
SOLUTION: UNDERGRADUATE                                                              55178
FEDERAL STAFFORD                                                                     41754
FEDERAL UNSUBSIDIZED STAFFORD                                                        39434
FEDERAL SUBSIDIZED CONSOLIDATION                                                      6735
FEDERAL UNSUBSIDIZED CONSOLIDATION                                                    6616
SOLUTION: HEALTH PROFESSIONS                                                          3585
FMC/TERI: ALTERNATIVE LOAN PROGRAM                                                    2984
REFINANCE                                                                             2784
SOLUTION: GRADUATE                                                                    2287
GROVE CITY LOAN PROGRAM                                                               1881
PARENT PLUS                                                                           1349
FMC/TERI                                                                              1220
GRADUATE PLUS                                                                          769
ACCESS GROUP: BAR EXAMINATION LOAN                                                     751
GROVE CITY LOAN PROGRAM (NEW BORROWER)                                                 661
ACCESS GROUP: LAW ACCESS LOAN                                                          630
SOLUTION: BAR EXAMINATION                                                              603
GRADUATE/PROFESSIONAL                                                                  575
GROVE CITY LOAN PROGRAM (SERIAL BORROWER)                                              360
MEDICAL PROFESSIONS LOAN PROGRAM                                                       339
FMC/TERI: GRADUATE/PROFESSIONAL                                                        195
SOLUTION: CONTINUING EDUCATION                                                         165
ACCESS GROUP: COMPREHENSIVE ACCESS LOAN                                                148
TERI GUARANTEED: CONTINUING EDUCATION                                                  128
ACCESS GROUP: GRADUATE ACCESS LOAN                                                     128
FMC/TERI: HEALTH PROFESSIONS                                                           124
MONTICELLO: UNDERGRADUATE; PNC NATIONAL COLLEGIATE: UNDERGRADUATE                       99
SOLUTION: HEALTH RESIDENCY                                                              96
FEDERAL UNSUBSIDIZED SPOUSAL CONSOLIDATION                                              76
ACCESS GROUP: MEDICAL RESIDENCY LOAN                                                    72
FMC/TERI: LEGACY NATIONAL CITY                                                          69
FEDERAL SUBSIDIZED SPOUSAL CONSOLIDATION                                                68
VILLANOVA LOAN PROGRAM                                                                  60
ACCESS GROUP: DENTAL RESIDENCY LOAN                                                     57
ACCESS GROUP: SPONSORED ACCESS LOAN                                                     55
ACCESS GROUP: BUSINESS ACCESS LOAN                                                      46
ACCESS GROUP: HEALTH ACCESS LOAN                                                        43
ACCESS GROUP: MEDICAL ACCESS LOAN                                                       28
ACESS GROUP: DENTAL ACCESS LOAN                                                         28
MONTICELLO: GRADUATE/PROFESSIONAL; PNC NATIONAL COLLEGIATE: GRADUATE/PROFESSIONAL       21
K-12                                                                                    18
MEDICAL PROFESSIONS RESIDENCY LOAN PROGRAM                                              16
OLD TERI: LEGACY NATIONAL CITY                                                          16
FEDERAL CONSOLIDATION                                                                   14
PNC RESOURCE LOAN PROGRAM                                                               13
TERI GUARANTEED: GRADUATE/PROFESSIONAL                                                   6
MONTICELLO: K-12; PNC NATIONAL COLLEGIATE: K-12                                          5
SUPPLEMENTAL LOANS FOR UNDERGRADUATES                                                    4
MONTICELLO: CONTINUING EDUCATION; PNC NATIONAL COLLEGIATE: CONTINUING EDUCATION          3
TERI GUARANTEED: ALTERNATIVE LOAN PROGRAM                                                2
SPOUSAL CONSOLIDATION                                                                    1
FMC/TERI: RESIDENCY LOAN                                                                 1
Name: count, dtype: int64

In [52]:
loan_tape['categorization'].value_counts()

categorization
UNDERGRADUATE                             135715
GRADUATE/PROFESSIONAL                      16822
UNKNOWN-FEDERAL                            13609
UNDERGRADUATE OR GRADUATE/PROFESSIONAL      3709
UNKNOWN-PERL                                2126
CONTINUING EDUCATION                         296
K-12                                          23
Name: count, dtype: int64

In [45]:
loan_tape['repayment_plan'].value_counts()

repayment_plan
FULLY DEFERRED         136894
IMMEDIATE REPAYMENT     24250
INTEREST ONLY            9419
UNKNOWN                  1148
OTHER - MCKINSEY          575
Name: count, dtype: int64

In [46]:
payment_history['final_status'].value_counts()

final_status
E.CURRENT                 2736893
A.SCHOOL                   421712
C.DEFERMENT                150440
S. PIF_CREDIT_BALANCES     149779
B.GRACE                     81477
F. 1-15                     74132
G. 16-29                    29487
D.FORBEARANCE               21674
H. 30-59                    18062
I. 60-89                     8871
Q.BANKRUPTCY                 5640
J. 90-119                    5277
R. CHARGED-OFF               3927
K. 120-149                    298
L. 150-179                     27
O. 240-269                     15
M. 180-209                      9
P. 270+                         9
N. 210-239                      4
Name: count, dtype: int64

In [49]:
payment_history[payment_history['gcl']>0]

,acct_id_mask,load_date,sub_products,final_status,repayment_dt_vintage,cosign_ind_x,open_dt_vintage,dec_fico_scr,balance,dpd30_bal,dpd60_bal,dpd90_bal,gcl
461,14,2025-09-30,Solution,R. CHARGED-OFF,2012.0,Others,2012,681.0,0.0,0.0,0.0,0.0,2668.83
3784,121,2025-09-30,Solution,R. CHARGED-OFF,2010.0,Others,2009,783.0,0.0,0.0,0.0,0.0,1334.21
4418,140,2024-08-31,Solution,R. CHARGED-OFF,2013.0,Cosigned,2013,716.0,0.0,0.0,0.0,0.0,10441.95
5336,169,2023-11-30,Solution,R. CHARGED-OFF,2013.0,Others,2008,757.0,0.0,0.0,0.0,0.0,6726.21
5454,172,2025-12-31,Solution,R. CHARGED-OFF,2014.0,Cosigned,2013,829.0,0.0,0.0,0.0,0.0,4027.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3694941,124769,2023-08-31,Grove City,R. CHARGED-OFF,2021.0,Noncosigned,2017,0.0,0.0,0.0,0.0,0.0,14116.66
3695679,124799,2025-11-30,Grove City,R. CHARGED-OFF,2018.0,Noncosigned,2016,0.0,0.0,0.0,0.0,0.0,9588.62
3696154,124815,2023-12-31,Grove City,R. CHARGED-OFF,2023.0,Cosigned,2022,696.0,0.0,0.0,0.0,0.0,2212.24
3697208,124858,2024-05-31,Grove City,R. CHARGED-OFF,2009.0,Others,2008,0.0,0.0,0.0,0.0,0.0,3894.38
3700120,124978,2024-12-31,PERL,R. CHARGED-OFF,2024.0,Noncosigned,2024,709.0,0.0,0.0,0.0,0.0,71234.64

In [50]:
payment_history[payment_history['acct_id_mask'] == 140]

,acct_id_mask,load_date,sub_products,final_status,repayment_dt_vintage,cosign_ind_x,open_dt_vintage,dec_fico_scr,balance,dpd30_bal,dpd60_bal,dpd90_bal,gcl
4398,140,2022-12-31,Solution,E.CURRENT,2013.0,Cosigned,2013,716.0,10845.97,0.00,0.00,0.00,NaN
4399,140,2023-01-31,Solution,E.CURRENT,2013.0,Cosigned,2013,716.0,10797.22,0.00,0.00,0.00,NaN
4400,140,2023-02-28,Solution,E.CURRENT,2013.0,Cosigned,2013,716.0,10797.22,0.00,0.00,0.00,NaN
4401,140,2023-03-31,Solution,E.CURRENT,2013.0,Cosigned,2013,716.0,10735.86,0.00,0.00,0.00,NaN
4402,140,2023-04-30,Solution,E.CURRENT,2013.0,Cosigned,2013,716.0,10678.06,0.00,0.00,0.00,NaN
4403,140,2023-05-31,Solution,E.CURRENT,2013.0,Cosigned,2013,716.0,10616.51,0.00,0.00,0.00,NaN
4404,140,2023-06-30,Solution,E.CURRENT,2013.0,Cosigned,2013,716.0,10557.60,0.00,0.00,0.00,NaN
4405,140,2023-07-31,Solution,E.CURRENT,2013.0,Cosigned,2013,716.0,10494.96,0.00,0.00,0.00,NaN
4406,140,2023-08-31,Solution,H. 30-59,2013.0,Cosigned,2013,716.0,10494.96,10494.96,0.00,0.00,NaN
4407,140,2023-09-30,Solution,E.CURRENT,2013.0,Cosigned,2013,716.0,10376.74,0.00,0.00,0.00,NaN
4408,140,2023-10-31,Solution,E.CURRENT,2013.0,Cosigned,2013,716.0,10328.26,0.00,0.00,0.00,NaN
4409,140,2023-11-30,Solution,E.CURRENT,2013.0,Cosigned,2013,716.0,10313.31,0.00,0.00,0.00,NaN
4410,140,2023-12-31,Solution,H. 30-59,2013.0,Cosigned,2013,716.0,10313.31,10313.31,0.00,0.00,NaN
4411,140,2024-01-31,Solution,E.CURRENT,2013.0,Cosigned,2013,716.0,10090.08,0.00,0.00,0.00,NaN
4412,140,2024-02-29,Solution,E.CURRENT,2013.0,Cosigned,2013,716.0,10090.08,0.00,0.00,0.00,NaN
4413,140,2024-03-31,Solution,E.CURRENT,2013.0,Cosigned,2013,716.0,9960.43,0.00,0.00,0.00,NaN
4414,140,2024-04-30,Solution,E.CURRENT,2013.0,Cosigned,2013,716.0,9960.43,0.00,0.00,0.00,NaN
4415,140,2024-05-31,Solution,H. 30-59,2013.0,Cosigned,2013,716.0,9960.43,9960.43,0.00,0.00,NaN
4416,140,2024-06-30,Solution,I. 60-89,2013.0,Cosigned,2013,716.0,9960.43,9960.43,9960.43,0.00,NaN
4417,140,2024-07-31,Solution,J. 90-119,2013.0,Cosigned,2013,716.0,9960.43,9960.43,9960.43,9960.43,NaN
4418,140,2024-08-31,Solution,R. CHARGED-OFF,2013.0,Cosigned,2013,716.0,0.00,0.00,0.00,0.00,10441.95
4419,140,2024-09-30,Solution,S. PIF_CREDIT_BALANCES,2013.0,Cosigned,2013,716.0,0.00,0.00,0.00,0.00,NaN
4420,140,2024-10-31,Solution,S. PIF_CREDIT_BALANCES,2013.0,Cosigned,2013,716.0,0.00,0.00,0.00,0.00,NaN
4421,140,2024-11-30,Solution,S. PIF_CREDIT_BALANCES,2013.0,Cosigned,2013,716.0,0.00,0.00,0.00,0.00,NaN
4422,140,2024-12-31,Solution,S. PIF_CREDIT_BALANCES,2013.0,Cosigned,2013,716.0,0.00,0.00,0.00,0.00,NaN